#index:
#    path: /
#    controller: App\Controller\DefaultController::index
micro_post_index:
    path: /
    controller: App\Controller\MicroPostController::index

app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number